services:
  app:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  k6:
    build: .
    container_name: k6-builder
    volumes:
      - ./output:/output
    command: ["cp", "/k6", "/output/k6"]

  k6-run:
    image: grafana/k6
    container_name: k6-runner
    volumes:
      - ./output/k6:/usr/bin/k6
      - ./script.js:/script.js
    entrypoint: ["/usr/bin/k6"]
    command: ["run", "/script.js"]
    depends_on:
      - prometheus